spring:
  application:
    name: backend-project
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/careerBTI # DB ??
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      read-only: false # ??? ?? ??

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    open-in-view: true

data:
  init: true

jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRET_KEY}